### ISSUE TITLE
请问一个问题 关于也页面销毁的问题

### ISSUE THREAD

**Issue by aalj** [xybCoder/gank#6]
在进入一个页面的时候发出的请求，但是由于网络很慢请求没返回，这是关闭了这页面， 在该项目里面presenter解绑以后iView置空了，抛出了空指针异常，  对于这种情况，如果不采用那种在使用iView的时候进行空判断 怎么解决比较好。

**Comment by xybCoder** [comment]
有两种办法，一在ondestory前取消网络请求；二在接口基类回调做个判断，view为空直接return发自我的iPhone------------------ 原始邮件 ------------------发件人: aalj  <notifications@github.com>发送时间: 2018年10月12日 16:13收件人: xybCoder/gank <gank@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[xybCoder/gank] 请问一个问题 关于也页面销毁的问题 (#6)在进入一个页面的时候发出的请求，但是由于网络很慢请求没返回，这是关闭了这页面， 在该项目里面presenter解绑以后iView置空了，抛出了空指针异常，  对于这种情况，如果不采用那种在使用iView的时候进行空判断 怎么解决比较好。

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/xybCoder/gank","title":"xybCoder/gank","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/xybCoder/gank"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"请问一个问题 关于也页面销毁的问题 (#6)"}],"action":{"name":"View Issue","url":"https://github.com/xybCoder/gank/issues/6"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/xybCoder/gank/issues/6",
"url": "https://github.com/xybCoder/gank/issues/6",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "请问一个问题 关于也页面销毁的问题 (#6)",
"sections": [
{
"text": "",
"activityTitle": "**aalj**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@aalj",
"facts": [
{
"name": "Repository: ",
"value": "xybCoder/gank"
},
{
"name": "Issue #: ",
"value": 6
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"xybCoder/gank\",\n\"issueId\": 6,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"xybCoder/gank\",\n\"issueId\": 6\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/xybCoder/gank/issues/6"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 392428913\n}"
}
],
"themeColor": "26292E"
}
]
